services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Set this in Render dashboard for security
